# Generated by Django 5.0.14 on 2025-08-15 14:27

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_post_tags"),
    ]

    operations = [
        TrigramExtension()
    ]
